QuanLyPhongKham3/Models/Prescription.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Prescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prescription()
        {
            this.PrescriptionDetails = new HashSet<PrescriptionDetails>();
        }
    
        public int ID { get; set; }
        public int IdStaff { get; set; }
        public int IDCustomer { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateOfCreate { get; set; }
        public string Symptom { get; set; }
        public string Diagnosis { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionDetails> PrescriptionDetails { get; set; }
        public virtual Staff Staff { get; set; }
    }
}

QuanLyPhongKham3/Controllers/PrescriptionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using QuanLyPhongKham3.Models;

namespace QuanLyPhongKham3.Controllers
{
    [Authorize(Roles = "Admin,Doctor")]
    public class PrescriptionsController : Controller
    {
        private QLPKEntities db = new QLPKEntities();

        // GET: Prescriptions
        public ActionResult Index()
        {
            string useid =this.User.Identity.GetUserId();
            Staff doctor=db.Staff.Where(x => x.UserId == useid).FirstOrDefault();
            Response.AddHeader("Refresh", "5");
            return View(db.Prescription.Where(x => x.Status == "New" && x.DateOfCreate == DateTime.Today && x.IdStaff==doctor.ID).ToList());
        }

        public ActionResult Add(int patient_id, int doctor_id)
        {
            Customer customer = db.Customer.Find(patient_id);

            Prescription prescription = new Prescription
            {
                IDCustomer = patient_id,
                IdStaff = doctor_id,
                Status = "New",
                DateOfCreate = DateTime.Today,


            };
            try
            {
                db.Prescription.Add(prescription);
                db.SaveChanges();
                return Json(new
                {
                    status = "OK"
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    status = "ERROR",
                    message = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
            ////   ViewBag.Staff = new SelectList(db.AspNetRoles.Where(role => role.Name.Contains("Doctor")).ToList(), "Name", "Name", "Employee");
            //     DoctorCart cart = DoctorCart.getInstance();
            //     cart.Add(item);
            //     //return View(DoctorCart.getInstance().List.Values);
        }


        // GET: Prescriptions
        public ActionResult Apply(int? id)
        {
            Prescription prescription = db.Prescription.Find(id);
            if (prescription == null)
            {
                return HttpNotFound();
            }
            var medicines = db.Medicine.Select(x => new { Id = x.ID, Name = x.Name + " (" + x.Unit + ")" });
            ViewBag.IDMedicine = new SelectList(medicines, "Id", "Name");
            ViewBag.prescription = prescription;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Apply([Bind(Include = "IDPrescription,IDMedicine,Quantity,Morning,Noon,Afternoon,Night,Using")] PrescriptionDetails detail)
        {

            if (ModelState.IsValid)
            {
                db.PrescriptionDetails.Add(detail);
                db.SaveChanges();
                return RedirectToAction("Apply", new { id = detail.IDPrescription });
            }

            var medicines = db.Medicine.Select(x => new { Id = x.ID, Name = x.Name + " (" + x.Unit + ")" });
            ViewBag.MedicineId = new SelectList(medicines, "Id", "Name");
            ViewBag.prescription = db.Prescription.Find(detail.IDPrescription);
            return View();
        }

        public ActionResult Transfer(int? detail_id, int? pres_id)
        {
            Prescription prescription = db.Prescription.Find(pres_id);
            try
            {
                prescription.Status = "Unpaid";
                db.Entry(prescription).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new
                {
                    
                    status = "OK",
                }, JsonRequestBehavior.AllowGet);
                

            }
            catch (Exception ex)
            {
                return Json(new
                {
                    status = "ERROR",
                    message = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }

        }


        // GET: Prescriptions/Details/5
        public ActionResult Details(int? pres_id)
        {
            if (pres_id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prescription prescription = db.Prescription.Find(pres_id);
            //try
            //{
            //    return Json(new
            //    {
            //        status = "OK"
            //    }, JsonRequestBehavior.AllowGet);
            //}
            //catch (Exception ex)
            //{
            //    return Json(new
            //    {
            //        status = "ERROR",
            //        message = ex.Message
            //    }, JsonRequestBehavior.AllowGet);
            //}
            if (prescription == null)
            {
                return HttpNotFound();
            }
            return View(prescription);
        }

        // GET: Prescriptions/Create
        public ActionResult Create()
        {
            ViewBag.PatientId = new SelectList(db.Customer, "Id", "Name");
            ViewBag.DoctorId = new SelectList(db.Staff, "Id", "Name");
            return View();
        }

        // POST: Prescriptions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DoctorId,PatientId,DateOfCreate,Symptom,Diagnosis,Status")] Prescription prescription)
        {
            if (ModelState.IsValid)
            {
                db.Prescription.Add(prescription);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PatientId = new SelectList(db.Customer, "Id", "Name", prescription.IDCustomer);
            ViewBag.DoctorId = new SelectList(db.Staff, "Id", "Name", prescription.IdStaff);
            return View(prescription);
        }

        // GET: Prescriptions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prescription prescription = db.Prescription.Find(id);
            if (prescription == null)
            {
                return HttpNotFound();
            }
            ViewBag.PatientId = new SelectList(db.Customer, "Id", "Name", prescription.IDCustomer);
            ViewBag.DoctorId = new SelectList(db.Staff, "Id", "Name", prescription.IdStaff);
            return View(prescription);
        }

        // POST: Prescriptions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DoctorId,PatientId,DateOfCreate,Symptom,Diagnosis,Status")] Prescription prescription)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prescription).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PatientId = new SelectList(db.Customer, "Id", "Name", prescription.IDCustomer);
            ViewBag.DoctorId = new SelectList(db.Staff, "Id", "Name", prescription.IdStaff);
            return View(prescription);
        }

        // GET: Prescriptions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prescription prescription = db.Prescription.Find(id);
            if (prescription == null)
            {
                return HttpNotFound();
            }
            return View(prescription);
        }

        // POST: Prescriptions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prescription prescription = db.Prescription.Find(id);
            db.Prescription.Remove(prescription);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyPhongKham3/Views/Prescriptions/Apply.cshtml
@model QuanLyPhongKham3.Models.PrescriptionDetails

@{
    ViewBag.Title = "Apply";
    QuanLyPhongKham3.Models.Prescription dt = ViewBag.prescription;
}

<h2>Apply</h2>

<div>
    <h4>ID: @(dt.ID.ToString("000000"))</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Date:
        </dt>

        <dd>
            @(dt.DateOfCreate.ToString("dd-MM-yyyy"))
        </dd>

        <dt>
            Patient:
        </dt>

        <dd>
            @(dt.Customer.Name)
        </dd>

        <dt>
            Doctor:
        </dt>

        <dd>
            @(dt.Staff.Name)
        </dd>

        <dt>
            Status:
        </dt>

        <dd>
            @(dt.Status)
        </dd>


    </dl>
</div>
<table class="table">
    <tr>
        <th>
            No
        </th>
        <th>
            Medicine name
        </th>
        <th>
            Unit
        </th>
        <th class="text-right">
            Quantity
        </th>
        <th class="text-right">
            Morning
        </th>
        <th class="text-right">
            Afternoon
        </th>
        <th class="text-right">
            Noon
        </th>
        <th class="text-right">
            Night
        </th>
        <th>
            Usage
        </th>
    </tr>

    @foreach (var item in dt.PrescriptionDetails.Select((x, i) => new { Data = x, Index = i }))
    {
        <tr>
            <td>
                @(item.Index + 1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data.Medicine.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data.Medicine.Unit)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.Data.Quantity)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.Data.Morning)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.Data.Noon)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.Data.Afternoon)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.Data.Night)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data.Using)
            </td>

        </tr>
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <tr>
            <td colspan="3">
                @Html.HiddenFor(model => model.IDPrescription, new { Value = dt.ID })
                @Html.DropDownList("IDMedicine", null, htmlAttributes: new { @class = "form-control", style = "width: 300px;" })
            </td>
            <td>
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @Value = "0", @class = "form-control", style = "width: 100%;" } })
            </td>
            <td>
                @Html.EditorFor(model => model.Morning, new { htmlAttributes = new { @Value = "0", @class = "form-control", style = "width: 100%;" } })
            </td>
            <td>
                @Html.EditorFor(model => model.Noon, new { htmlAttributes = new { @Value = "0", @class = "form-control", style = "width: 100%;" } })
            </td>
            <td>
                @Html.EditorFor(model => model.Afternoon, new { htmlAttributes = new { @Value = "0", @class = "form-control", style = "width: 100%;" } })
            </td>
            <td>
                @Html.EditorFor(model => model.Night, new { htmlAttributes = new { @Value = "0", @class = "form-control", style = "width: 100%;" } })
            </td>
            <td>
                @Html.EditorFor(model => model.Using, new { htmlAttributes = new { @Value = "Drink", @class = "form-control", style = "width: 100%;" } })
            </td>
        </tr>
        <tr>
            <td colspan="9" class="text-right">
                <input type="submit" value="Add" class="btn btn-info" />
            </td>
            <td type="button" class="add-to-cart" data-id="@dt.ID">
                <button style="color: #fff; background-color:#5bc0de;border-color:#46b8da ;border-radius:5px;height:33px">Transfer</button>
            </td>

        </tr>
    }
</table>
@section Scripts{
    <script src="https://lipis.github.io/bootstrap-sweetalert/lib/sweet-alert.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <link href="~/Scripts/sweetalert.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/sweetalert.js"></script>
    <script language="javascript">
        $(".add-to-cart").click(function () {
            var tr = $(this).closest("tr");
            var pres_id = $(this).data("id");

            $.ajax({
                url: '/Prescriptions/Transfer',
                method: 'GET',
                async: true,
                cache: false,
                data: {
                    pres_id: pres_id,



                },
                beforeSend: function () {
                    swal("Please wait...");
                }
            }).done(function (result) {
                if (result.status == "OK") {
                    swal("Success!");
                    window.location.href = '@Url.Action("Index", "Prescriptions")'
                    tr.remove();
                }
                else if (result.status == "ER") {
                    //$("#fb").html(result.data);
                    alert("Error!", "Error!", result.data);
                }

            }).fail(function (xhr, status) {
                //$("#fb").html(status);
                swal("failed", "Error!", status);
            }).always(function () {
                //$("#fb").html("");
            })
        })
    </script>

}

QuanLyPhongKham3/Views/Prescriptions/Create.cshtml
@model QuanLyPhongKham3.Models.Prescription

@{
    ViewBag.Title = "Create";
}

<h2>Toa thuốc mới</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @**@
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.IdStaff, "Người lập toa", htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-xs-2">
            @Html.DropDownList("IdStaff", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdStaff, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateOfCreate, "Ngày lập toa", htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-xs-2">
            @Html.EditorFor(model => model.DateOfCreate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateOfCreate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IDCustomer, "Tên bệnh nhân", htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-xs-2">
            @Html.DropDownList("IDCustomer", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IDCustomer, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Symptom, "Triệu chứng", htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-xs-4">
            @Html.TextAreaFor(model => model.Symptom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Symptom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status, "Trạng thái", htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>
    <div style="padding-left: 50px;padding-right: 30px;padding-top:50px;" class="container">
        <h2 class="text-center">Đơn thuốc</h2>

        <table class="table table-dark table-striped table-hover tbl_code_with_mark">
            <tr>
                <th>Tên thuốc</th>
                <th>Số lượng</th>
                <th>Cách dùng</th>
                <th>Liều lượng</th>
                <th>Option</th>
            </tr>
            <tr>
                <td>
                    <div class="col" type="text">
                        @Html.DropDownList("IDMedicine", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDMedicine, "", new { @class = "text-danger" })
                    </div>
                </td>
                <td>
                    <div class="col">
                        @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Medicine.Count, "", new { @class = "text-danger" })
                    </div>
                </td>
                <td>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Using, new { htmlAttributes = new { @class = "form-control Material_Serial" } })
                        @Html.ValidationMessageFor(model => model.Using, "", new { @class = "text-danger" })
                    </div>
                </td>

                <td>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Dosage, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dosage, "", new { @class = "text-danger" })
                    </div>
                </td>

                <td>
                    <span class="btn btn-sm btn-success btn_row_below_clone">Add</span> |
                    <span class="btn btn-sm btn-danger btn_row_delete">Delete</span>
                </td>
            </tr>
        </table>
    </div>

    <div class="form-group" style="margin-left:20%">
        <div class="col-md-offset-2 col-md-10">
            <input style="height: 50px; width: 500px" type="submit" value="Tạo" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại danh sách toa thuốc", "Index")
</div>
@*
        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")

    }*@
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script>
    $('.Material_Serial').keypress(function (event) {

        disableEnterKey(event);

    });
</script>
<script>
    $(document).ready(function ($) {
        //--->add row at the end > start
        $(document).on('click', ".btn_row_add_below_end", function (e) {
            var tableBody = $(document).find('.tbl_code_with_mark').find("tbody");
            var trLast = tableBody.find("tr:last");
            var trNew = trLast.clone();
            trLast.after(trNew);
        });
        //--->add row at the end > end


        //--->current row > new > start
        $(document).on('click', ".btn_row_below_new", function (e) {
            var r = $(this).closest('tr').clone();

            $.each(r.find('td'), function (i1, v1) {
                //clear all data/value in td/cell
                $(this).html('');
            });

            $(this).closest('tr').after(r);
        });
        //--->current row > new > end


        //--->current row > clone > start
        $(document).on('click', ".btn_row_below_clone", function (e) {
            var r = $(this).closest('tr').clone();
            $(this).closest('tr').after(r);
        });
        //--->current row > clone > end

        //--->current row > delete > start
        $(document).on('click', ".btn_row_delete", function (e) {
            var r = $(this).closest('tr').remove();
        });
        //--->current row > delete > end

    });
</script>

QuanLyPhongKham3/Views/Prescriptions/Delete.cshtml
@model QuanLyPhongKham3.Models.Prescription

@{
    ViewBag.Title = "Delete";
}



<h3>Bạn có muốn xóa toa thuốc này?</h3>
<div>
    <h4>Prescription</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Ngày lập toa")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfCreate)
        </dd>

        <dt>
            @Html.Label("Trạng thái")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.Label("Tên bệnh nhân")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>

        <dt>
            @Html.Label("Tên thuốc")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Medicine.Name)
        </dd>

        <dt>
            @Html.Label("Người lập toa")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staff.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại danh sách toa thuốc", "Index")
        </div>
    }
</div>

QuanLyPhongKham3/Views/Prescriptions/Details.cshtml
@model QuanLyPhongKham3.Models.PrescriptionDetails

@{
    ViewBag.Title = "Details";
    QuanLyPhongKham3.Models.Prescription dt = ViewBag.prescription;
}




<h2>Apply</h2>

<div>
    <h4>ID: @(dt.ID.ToString("000000"))</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Date:
        </dt>

        <dd>
            @(dt.DateOfCreate.Value.ToString("dd-MM-yyyy"))
        </dd>

        <dt>
            Patient:
        </dt>

        <dd>
            @(dt.Customer.Name)
        </dd>

        <dt>
            Doctor:
        </dt>

        <dd>
            @(dt.Staff.Name)
        </dd>

        <dt>
            Status:
        </dt>

        <dd>
            @(dt.Status)
        </dd>

       

    </dl>
</div>
<table class="table">
    <tr>
        <th>
            No
        </th>
        <th>
            Medicine name
        </th>
        <th>
            Unit
        </th>
        <th class="text-right">
            Quantity
        </th>
        <th class="text-right">
            Morning
        </th>
        <th class="text-right">
            Afternoon
        </th>
        <th class="text-right">
            Noon
        </th>
        <th class="text-right">
            Night
        </th>
        <th>
            Usage
        </th>
    </tr>

    @foreach (var item in dt.PrescriptionDetails.Select((x, i) => new { Data = x, Index = i }))
    {
        <tr>
            <td>
                @(item.Index + 1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data.Medicine.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data.Medicine.Unit)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.Data.Quantity)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.Data.Morning)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.Data.Noon)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.Data.Afternoon)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.Data.Night)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data.Using)
            </td>
        </tr>
    }
   
    }
</table>

QuanLyPhongKham3/Views/Prescriptions/Index.cshtml
@model IEnumerable<QuanLyPhongKham3.Models.Prescription>


@{ ViewBag.Title = "Index"; }


<table class="table" onload="JavaScript:timedRefresh(5000);">
    <tr>
        <th class="text-right">
            No.
        </th>
        <th>
            @Html.Label("Name")
        </th>
        <th>
            @Html.Label("Doctor Name")
        </th>
        <th>
            @Html.Label("Status")
        </th>
        <th>
            @Html.Label("Date of Create")
        </th>

        <th>



        </th>
    </tr>
    @{ int i = 0; }
    @foreach (var item in Model)
    {
        <tr>
            <td class="text-right">
                @(++i)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Customer.Name)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Staff.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfCreate)
            </td>

            <td style="border:solid;background-color:aqua;width:30px">
                @Html.ActionLink("Apply", "Apply", new { id = item.ID})

            </td>

        </tr>
}

</table>

@section Scripts{
    <script type="text/javascript">
        function timedRefresh(timeoutPeriod) {
            setTimeout(function () {
                location.reload(true);
            }, timeoutPeriod);
        }



        

    </script>

}

QuanLyPhongKham3/Views/Prescriptions/Transfer.cshtml
@model IEnumerable<QuanLyPhongKham3.Models.Prescription>

@*@{
    ViewBag.Title = "Transfer";
    QuanLyPhongKham3.Models.Prescription dt = ViewBag.prescription;
}

<div>
    <h4>ID: @(dt.ID.ToString("000000"))</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Date:
        </dt>

        <dd>
            @(dt.DateOfCreate.ToString("dd-MM-yyyy"))
        </dd>

        <dt>
            Patient:
        </dt>

        <dd>
            @(dt.Customer.Name)
        </dd>

        <dt>
            Doctor:
        </dt>

        <dd>
            @(dt.Staff.Name)
        </dd>

        <dt>
            Status:
        </dt>

        <dd>
            @(dt.Status)
        </dd>


    </dl>
</div>*@


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Staff.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfCreate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Afternoon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Night)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Using)
        </th>*@


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Staff.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfCreate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Afternoon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Night)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Using)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Prescription.Symptom)
            </td>*@

        </tr>
    }

</table>