QuanLyPhongKham3/Models/Medicine.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.PrescriptionDetails = new HashSet<PrescriptionDetails>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int IDMedicineType { get; set; }
        public string Unit { get; set; }
        public int Count { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
    
        public virtual MedicineType MedicineType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionDetails> PrescriptionDetails { get; set; }
    }
}

QuanLyPhongKham3/Models/MedicineType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicineType()
        {
            this.Medicine = new HashSet<Medicine>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine> Medicine { get; set; }
    }
}

QuanLyPhongKham3/Controllers/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyPhongKham3.Models;
using PagedList;//Must install
namespace QuanLyPhongKham3.Controllers
{
    [Authorize(Roles ="Dispenser,Admin")]
    public class MedicinesController : Controller
    {
        private QLPKEntities db = new QLPKEntities();

        // GET: Medicines
        public ActionResult Index(string searchBy, string search, int? page, string sortBy)
        {

            var medicine = db.Medicine.Include(m => m.MedicineType);
            ViewBag.NameSort = String.IsNullOrEmpty(sortBy) ? "Name desc" : "";
            ViewBag.UnitSort = sortBy == "Unit" ? "Unit desc" : "Unit";
            ViewBag.TypeSort = sortBy == "Type" ? "Type desc" : "Type";
            var medicines = db.Medicine.AsQueryable();

            if (searchBy == "Unit")
            {
                medicines = medicines.Where(x => x.Unit == search || search == null);
            }
            else
            {
                medicines = medicines.Where(x => x.Name.StartsWith(search) || search == null);
            }
            

            switch (sortBy)
            {
                case "Name desc":
                    medicines = medicines.OrderByDescending(x => x.Name);
                    break;
                case "Unit desc":
                    medicines = medicines.OrderByDescending(x => x.Unit);
                    break;
                case "Unit":
                    medicines = medicines.OrderBy(x => x.Unit);
                    break;
                case "Type desc":
                    medicines = medicines.OrderByDescending(x => x.IDMedicineType);
                    break;
                case "Type":
                    medicines = medicines.OrderBy(x => x.IDMedicineType);
                    break;
                default:
                    medicines = medicines.OrderBy(x => x.Name);
                    break;
            }

            return View(medicines.ToPagedList(page ?? 1, 5));
            //return View(medicine.ToList());
        }

        // GET: Medicines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicine.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // GET: Medicines/Create
        public ActionResult Create()
        {
            ViewBag.IDMedicineType = new SelectList(db.MedicineType, "ID", "Name");
            return View();
        }

        // POST: Medicines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,IDMedicineType,Unit,Count,Cost,Price")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                db.Medicine.Add(medicine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDMedicineType = new SelectList(db.MedicineType, "ID", "Name", medicine.IDMedicineType);
            return View(medicine);
        }

        // GET: Medicines/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicine.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDMedicineType = new SelectList(db.MedicineType, "ID", "Name", medicine.IDMedicineType);
            return View(medicine);
        }

        // POST: Medicines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,IDMedicineType,Unit,Count,Cost,Price")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medicine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDMedicineType = new SelectList(db.MedicineType, "ID", "Name", medicine.IDMedicineType);
            return View(medicine);
        }

        // GET: Medicines/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicine.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // POST: Medicines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medicine medicine = db.Medicine.Find(id);
            db.Medicine.Remove(medicine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyPhongKham3/Views/Medicines/Create.cshtml
@model QuanLyPhongKham3.Models.Medicine

@{
    ViewBag.Title = "Create";
}

<h2>Insert New Medicine</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name,"Medicine Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDMedicineType, "Medicine Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
                @Html.DropDownList("IDMedicineType", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDMedicineType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit, "Unit", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, "Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, "Cost", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Price", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Insert" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Black", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyPhongKham3/Views/Medicines/Delete.cshtml
@model QuanLyPhongKham3.Models.Medicine

@{
    ViewBag.Title = "Delete";
}




<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Medicine Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.Label("Unit")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.Label("Number")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Count)
        </dd>

        <dt>
            @Html.Label("Cost")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.Label("Price")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.Label("Medicine Type")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedicineType.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" asp-route-id="@Model.ID" method="post">
            <input style="margin-left:12%" type="submit" value="Delete" class="btn btn-default" onclick="return functionConfirm(this)" />
            <br>
            @Html.ActionLink("Black", "Index")
        </div>
    }
</div>
@section Scripts{
    <script src="https://lipis.github.io/bootstrap-sweetalert/lib/sweet-alert.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <link href="~/Scripts/sweetalert.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/sweetalert.js"></script>
    <script type="text/javascript">
        function functionConfirm(event) {
            swal({
                title: 'Are You Sure?',
                text: "You will not be able to recover this item",
                type: 'warning',
                showCancelButton: true,
                cancelButtonText: 'No',
                cancelButtonClass: 'btn btn-danger',
                showConfirmButton: true,
                confirmButtonText: 'Yes',
                confirmButtonClass: 'btn btn-success'
            }, function (isConfirm) {
                if (isConfirm) {
                    $('form').submit();
                    return true;
                } else {
                    return false;
                }
            });
            return false;
        }
    </script>

}

QuanLyPhongKham3/Views/Medicines/Details.cshtml
@model QuanLyPhongKham3.Models.Medicine

@{
    ViewBag.Title = "Details";
}

<h2>Detail</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("ID")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.Label("Medicine Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.Label("Unit")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.Label("Number")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Count)
        </dd>

        <dt>
            @Html.Label("Cost")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.Label("Price")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.Label("Medicine Type")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedicineType.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Black", "Index")
</p>

QuanLyPhongKham3/Views/Medicines/Edit.cshtml
@model QuanLyPhongKham3.Models.Medicine

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Medicine Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDMedicineType, "Medicine Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
                @Html.DropDownList("IDMedicineType", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDMedicineType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit, "Unit", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, "Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, "Cost", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Price", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" onclick="return functionConfirm(this)" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Black", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval");

    <script src="https://lipis.github.io/bootstrap-sweetalert/lib/sweet-alert.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <link href="~/Scripts/sweetalert.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/sweetalert.js"></script>
    <script type="text/javascript">
        function functionConfirm(event) {
            swal({
                title: 'Are You Sure?',
                text: "Once modified, you will not be able to recover this medicine profile!",
                type: 'warning',
                showCancelButton: true,
                cancelButtonText: 'No',
                cancelButtonClass: 'btn btn-danger',
                showConfirmButton: true,
                confirmButtonText: 'Yes',
                confirmButtonClass: 'btn btn-success'
            }, function (isConfirm) {
                if (isConfirm) {
                    $('form').submit();
                    swal("Good job!", 'success', "success");
                    return true;
                } else {
                    return false;
                }
            });
            return false;
        }
    </script>


}

QuanLyPhongKham3/Views/Medicines/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model  PagedList.IPagedList<QuanLyPhongKham3.Models.Medicine>

@{
    ViewBag.Title = "Index";
}

<h2>List of drugs</h2>
@using (@Html.BeginForm("Index", "Medicines", FormMethod.Get))
{
    <b>Sort By:</b>
    @Html.RadioButton("searchBy", "Name", true) <text>Name</text>
    @Html.RadioButton("searchBy", "Unit") <text>Unit</text>
    <br />
    @Html.Editor("search", new { htmlAttributes = new { @class = "", placeholder = "Please enter medicine name" } })
    <input type="submit" value="search" />
}

<p>
    @Html.ActionLink("Insert Drug", "Create")
</p>

<div>
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Name", "Index", new { sortBy = ViewBag.NameSort, searchBy = Request["searchBy"], search = Request["search"] })
            </th>
            <th>
                @Html.ActionLink("Unit", "Index", new { sortBy = ViewBag.UnitSort, searchBy = Request["searchBy"], search = Request["search"] })
            </th>
            <th>
                @Html.Label("Number")
            </th>
            <th>
                @Html.Label("Cost")
            </th>
            <th>
                @Html.Label("Price")
            </th>
            <th>
                @Html.ActionLink("Type", "Index", new { sortBy = ViewBag.TypeSort })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Unit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Count)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MedicineType.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Detail", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchBy = Request.QueryString["searchBy"], search = Request.QueryString["search"], sortBy = Request["sortBy"] }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })
</div>